### ISSUE TITLE
Amoled Background (Pure Black)

### ISSUE THREAD

**Issue by Rajala1404** [lanis-mobile/lanis#236]
I think it would be pretty nice to Implement an Amoled Theme (Pure Black Background) because on AMOLED displays pure black looks really good (at least in my opinion). I already have a implementation for this Feature that still Supports Material You Color Theming (except for the Background of course). Some People argue that Pure Black is bad because it makes for them it more difficult to read the Text but that shouldn't be a Problem because the Small Text are in there Chips that are Themed by Material You. My Implementation is still not Final because the App needs to be restart if you switch to AMOLED or back from AMOLED but that can be fixed by a Popup that Gives a Button to Restart or something like that. After I'm done i would open a Pull Request. Here are some Pictures of my Implementation, just need Feedback if that would be good: 
![combined1](https://github.com/alessioC42/lanis-mobile/assets/115874847/15fd5075-f277-43ee-bc4c-4dcf47fab0aa)
![combined2](https://github.com/alessioC42/lanis-mobile/assets/115874847/8e01923a-e4c3-45bc-be05-f2260d050693)
![combined3](https://github.com/alessioC42/lanis-mobile/assets/115874847/7dae4387-b934-46cf-ba7c-37c9e1e3bce7)
The Background of Timetable Popup is not Pure Black that just looks like that on the Screenshot or maybe its just my Crappy TV Screen

**Comment by alessioC42** [comment]
This should be an PR? Not an issue?

**Comment by Rajala1404** [comment]
Oh bruh, sorry my fault, at first i clicked issue for feature request.
